# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Herren' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Herren

  # Network
  pod 'Moya', '~> 14.0'
  
  # UI
  pod 'SnapKit', '~> 5.0.0'
  
  # Utility
  pod 'Kingfisher', '~> 5.0'

  target 'HerrenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HerrenUITests' do
    # Pods for testing
  end

end
